# This service will be listening over port 9010
server:
  port: '9040'

spring:

  # Service Name using which other services locates its instances from Service Registry
  application:
    name: domain-event-utils

  # JPA specific configurations
#  jpa:
#    show-sql: 'true'

# Logging configurations for Spring, Apache Kafka
#logging:
#  level:
#    org:
#      springframework: INFO
#      apache:
#        kafka:
#          common: INFO
#          clients:
#            consumer: INFO
#            producer: INFO
