# This service will be listening over port 9010
server:
  port: '9011'

spring:

  # Service Name using which other services locates its instances from Service Registry
  application:
    name: product-catalog-service

  # Database configurations: Postgresql   
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/onlinestore
    username: postgres
    password: password

  # JPA specific configurations
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

    # Configuration to resolve error Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'      

# Details of Service Discovery to which this service registers itself so other services can discover its instances and call it
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Pub/Sub Topics (Apache Kafka)
onlinestore:
  inventory:
    events:
      topic:
        name: InventoryEventsTopic
